### ISSUE TITLE
萌新提问

### ISSUE THREAD

**Issue by shijianzugouniai** [lyc8503/ConwaysGameOfLife#1]
博主，如果想学习这个demo的话，有哪些知识点需要注意呢？

**Comment by lyc8503** [comment]
我这段代码只用了 C 语言的基础语法和简单的一些 api, 将地图分块存储的过程中自己实现了链表, 你可以从 `main.c` 开始逐层阅读代码学习其中的部分写法.

**Comment by shijianzugouniai** [comment]
感谢博主您的回答，请问哪里可以sponsor呢？

**Comment by lyc8503** [comment]
> 感谢博主您的回答，请问哪里可以sponsor呢？

贴在了我的 Blog https://blog.lyc8503.site/about/

**Comment by shijianzugouniai** [comment]
感谢，已sponsor(希望大佬不要建议钱少)

**Comment by lyc8503** [comment]
> 感谢，已sponsor(希望大佬不要建议钱少)

感谢你的 sponsor, 祝你学习顺利!
